title: "Tierarztpraxis Kaiserstraße"

url: "http://tierarztpraxis-kaiserstrasse.at"

author: "Elfriede Koppensteiner, Dr."

description: "Leistungen und Behandlungsmöglichkeiten der Tierarztpraxis Kaiserstraße"

logo: "/img/logo.png"

exclude:
- README.md

gems:
- jekyll-seo-tag
- jekyll-sitemap

safe: true
