title: "Tierarztpraxis Kaiserstraße"

url: "http://tierarztpraxis-kaiserstrasse.at"

author: "Elfriede Koppensteiner, Dr."

description: "Leistungen und Behandlungsmöglichkeiten der Tierarztpraxis Kaiserstraße"

logo: "/img/logo.png"

exclude:
- README.md

plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-admin

safe: true

prose:
  rooturl: '_includes'
  siteurl: 'tierarztpraxis-kaiserstrasse.at'
  
